name: Docker Build and Push

on:
  push:
    branches:
      - main # Trigger when pushing to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out hte repository
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bricksync-dsm:${{ github.sha }} .

      - name: Push Image to Dockerhub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bricksync-dsm:${{ github.sha }}
